name: inoutapp
description: App for tracking personal input and output.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Build number docs:
# - https://developer.android.com/studio/publish/versioning
# - https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Helpful commands:
# - flutter pub upgrade --major-versions
# - flutter pub outdated
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.17.2
  provider: ^6.0.5
  intl: ^0.18.1
  built_value: ^8.6.0
  built_collection: ^5.0.0
  rxdart: ^0.27.7
  url_launcher: ^6.1.14
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  google_sign_in: ^6.1.5
  firebase_ui_auth: ^1.8.0
  firebase_ui_oauth_google: ^1.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  # See analysis_options.yaml
  flutter_lints: ^2.0.0
  test: ^1.0.0
  build_runner: '>=1.0.0 <3.0.0'
  built_value_generator: ^8.6.2

# See also: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
